version: "3.7"
services:
  landingpage:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - "5080:80"
    volumes:
      - ./data-dev:/data
      - ./src:/var/www/landingpage
